config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
normalize:
  outputs:
    prod:
      dbname: mydatabase
      host: host.docker.internal
      pass: ranjith
      port: 5432
      schema: public
      threads: 8
      type: postgres
      user: postgres
  target: prod
